<?php

use Illuminate\Database\Seeder;
use App\Notification;

class NotificationsSeeder extends Seeder
{
    private $notifications = array();
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->setData();

        foreach ($this->notifications as $notification){
            $not = new Notification();
            $not->sender_ebox_id = $notification['sender_ebox_id'];
            $not->subject = $notification['subject'];
            $not->message = $notification['message'];
            $not->send_date = $notification['send_date'];
            $not->message_summary = $notification['message_summary'];
            $not->draft = $notification['draft'];
            $not->type = $notification['type'];
            $not->notification_type_id = $notification['notification_type_id'];
            $not->data = $notification['data'];
            $not->save();
        }
    }

    public function setData(){
        $notifications = array(
            array('id' => '1','sender_ebox_id' => '1','subject' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','message' => 'Please keep the message less than 141 characters. This is what will be delivered through SMSPlease keep the message less than 141 characters. This is what will be delivered through SMSPlease keep the message less than 141 characters. This is what will be delivered through SMSPlease keep the message less than 141 characters. This is what will be delivered through SMSPlease keep the message less than 141 characters. This is what will be delivered through SMSPlease keep the message less than 141 characters. This is what will be delivered through SMS','send_date' => '2017-01-26 06:10:18','message_summary' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '2','sender_ebox_id' => '1','subject' => 'About Posta','message' => 'The Postal history in Kenya dates from the early years of the 17th century. A Portuguese governor was installed in Mombasa in 1592 and official correspondence between the town and the outside world has been recorded from 1610 onwards, carried by ship to Arabia and India and transmitted to Europe by the overland route. Early letters from the interior of Kenya date from about 1848 when the missionaries sent their correspondence by native runners to the Coast for onward transmission.','send_date' => '2017-01-26 07:15:25','message_summary' => 'The Postal history in Kenya dates from the early years of the 17th century.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '3','sender_ebox_id' => '1','subject' => 'EMS International','message' => 'Items can be sent to over 3,000 destinations worldwide from over 285 acceptance centers countrywide. A track and trace system providing prompt information on delivery and effective monitoring is available for most of the destinations in over 75 countries. EMS Kenya also offers customs clearance services for incoming items that are dutiable.','send_date' => '2017-01-26 07:27:34','message_summary' => 'Items can be sent to over 3,000 destinations worldwide from over 285 acceptance centers countrywide.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '4','sender_ebox_id' => '1','subject' => 'EMS International','message' => 'Items can be sent to over 3,000 destinations worldwide from over 285 acceptance centers countrywide. A track and trace system providing prompt information on delivery and effective monitoring is available for most of the destinations in over 75 countries. EMS Kenya also offers customs clearance services for incoming items that are dutiable.','send_date' => '2017-01-26 07:29:35','message_summary' => 'Items can be sent to over 3,000 destinations worldwide from over 285 acceptance centers countrywide.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '5','sender_ebox_id' => '1','subject' => 'International Parcels','message' => 'Air and surface parcel services are available to practically every country in the world. Air parcels generally take 5 to 13 days, while surface parcels take 7 to 45 days. Surface airlifted (SAL) Parcels are air lifted to their destination countries and delivered as surface parcels upon arrival.

Since all parcels sent overseas need clearance from customs, declaration of contents at the post office is necessary.
Maximum weight of an individual international surface/air parcel varies from country to country but the maximum Universal Postal Union (UPU) weight is 31.5 kgs.','send_date' => '2017-01-26 07:34:16','message_summary' => 'Air and surface parcel services are available to practically every country in the world.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '6','sender_ebox_id' => '1','subject' => 'International Parcels','message' => 'Air and surface parcel services are available to practically every country in the world. Air parcels generally take 5 to 13 days, while surface parcels take 7 to 45 days. Surface airlifted (SAL) Parcels are air lifted to their destination countries and delivered as surface parcels upon arrival.

Since all parcels sent overseas need clearance from customs, declaration of contents at the post office is necessary.
Maximum weight of an individual international surface/air parcel varies from country to country but the maximum Universal Postal Union (UPU) weight is 31.5 kgs.','send_date' => '2017-01-26 07:36:19','message_summary' => 'Air and surface parcel services are available to practically every country in the world.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '7','sender_ebox_id' => '1','subject' => 'Domestic Money Order [As good as cash but 100% safer]','message' => 'Money transfer service which serves the institutions segment and the larger public.  To use this service you fill and present a Money Order form and cash to the Teller / Cashier who in turn gives a receipt and an Order to be mailed to the payee.     The Payee presents the order and identification document to the paying Posta outlet for cash payment.','send_date' => '2017-01-26 07:50:46','message_summary' => 'Money transfer service which serves the institutions segment and the larger public.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '8','sender_ebox_id' => '1','subject' => 'Posta Merchant Services','message' => 'Posta is recognized as one of the most distributed enterprise in terms of service delivery. Operating in all Kenyan counties having more than 300 branches distributed through out the country, this provides a reliable national network that can be harnessed by merchants seeking localized operations at an affordable cost.

Key to this is the EMS solution. As an international recognized courier service, Posta seeks to partner with businesses by offering parcel delivery solutions on a national scale.

Our mandate is not only availing the physical channel but also an automated approach of facilitating this. This is now possible through our merchant API(Application Programming Interface). The Posta Merchant API is Kenya’s first and only dispatch API that seeks to automate deliveries of parcels country wide. This is key for Online merchants keen to have their deliveries automated.','send_date' => '2017-01-26 08:01:06','message_summary' => 'Posta is recognized as one of the most distributed enterprise in terms of service delivery.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '9','sender_ebox_id' => '1','subject' => 'Franked Mail','message' => 'For busy mailrooms and mail registries in Companies, Institutions and Government offices, a franking Meter Machine provides a faster, more convenient alternative to affixing postage on mail. Franking meter machines are available from authorized dealers and vary in sizes depending on customer’s needs. A license is required to operate a franking meter machine which is issued through the machine dealer.

A franking meter is handy since it gives the flexibility of franking the postage conveniently within office comfort. This means that one can pay for postage without having to visit the post office. Besides, franked mail can also carry advertising messages/ information.','send_date' => '2017-01-26 08:08:03','message_summary' => 'Franking meter machines are available from authorized dealers and vary in sizes depending on customer’s needs','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '10','sender_ebox_id' => '1','subject' => 'Business Reply Service','message' => 'Business Reply Service is a simple and effective way to obtain responses from the direct marketing communication.It is available in envelope, leaflet and card format’ . BRS can be used to initiate customer service, request information, research the marketplace or to identify customer needs.

Companies/Institutions enclose return addressed envelopes into their clients’ mail or detachable coupons on the Direct mail marketing (DMM) material. The payment for the return postage is prepaid by the promoting company therefore simplifying the reply process as the customers respond/send feedback at no expense to them.

A license is issued to the promoting company to use the BRS service.  A deposit is required to cover the probable amount of postage and the handling fee and once responses are sent back to your address a debit is made from the amount deposited on a reducing balance.','send_date' => '2017-01-26 08:10:43','message_summary' => 'Business Reply Service is a simple and effective way to obtain responses from the direct marketing communication.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '11','sender_ebox_id' => '1','subject' => 'Private Mail','message' => 'Private letter box/bags is a uniquely addressable lockable box which offers a safe and secure means of accessing letters. These are delivery points for mail in Kenya as mails are sorted into these boxes/bags at the specific offices the mail is addressed. We have over 400,000 private letter boxes countrywide.','send_date' => '2017-01-26 08:12:40','message_summary' => 'Private letter box/bags is a uniquely addressable lockable box which offers a safe and secure means of accessing letters. ','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '12','sender_ebox_id' => '1','subject' => 'Private Mail','message' => 'Private letter box/bags is a uniquely addressable lockable box which offers a safe and secure means of accessing letters. These are delivery points for mail in Kenya as mails are sorted into these boxes/bags at the specific offices the mail is addressed. We have over 400,000 private letter boxes countrywide.','send_date' => '2017-01-26 08:14:41','message_summary' => 'Private letter box/bags is a uniquely addressable lockable box which offers a safe and secure means of accessing letters. ','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '13','sender_ebox_id' => '1','subject' => 'Posta Pesa','message' => 'Agency banking is the new initiative brought on board to encourage financial inclusion to the unbanked and underbanked communities.   Mainstream banks have partnered with Posta Kenya and through integration of the banks to PCK’s PostaPesa switch, these banks can now reach and transact with their customers from all corners of the country via POS gadgets deployed in PCK outlets.   Posta Kenya also operates as Telkos for money transfer services as an Agent e.g. M-Pesa and Airtel Money.','send_date' => '2017-01-26 08:21:13','message_summary' => 'Agency banking is the new initiative brought on board to encourage financial inclusion to the unbanked and underbanked communities.','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '14','sender_ebox_id' => '1','subject' => 'Direct Mail','message' => 'Posta direct mail marketing is specifically designed to cater for corporate clients from small enterprises to large established organizations targeting customers. Through our extensive Posta network, DMM enables you to advertise products and services through leaflets, brochures, booklets, cards or catalogues by communicating messages straight to the target intended for. This is done using over 400,000 private letter boxes at your disposal.

It has become the medium of choice for marketers who want a better return on investment on their advertising because it’s targeted and it’s efficient.','send_date' => '2017-01-26 08:26:17','message_summary' => 'Posta direct mail marketing is specifically designed to cater for corporate clients from small enterprises..','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '15','sender_ebox_id' => '1','subject' => 'Test','message' => 'Test','send_date' => '2017-01-26 10:36:35','message_summary' => 'Test','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '16','sender_ebox_id' => '1','subject' => 'Alert','message' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS Please keep the message less than 141 characters. This is what will be delivered through SMS','send_date' => '2017-01-26 10:39:34','message_summary' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '17','sender_ebox_id' => '1','subject' => 'How Trump has already taken us into full-on \'Nineteen Eighty-Four\' territory','message' => 'When we started the Dystopia Project two weeks ago, with the aim of writing a story on every dystopian novel that might apply to the Trump presidency, we figured it would be a while before we had reason to cover the heavyweight champ of the genre: Nineteen Eighty-Four. 

George Orwell\'s 1949 classic is about a state that is totalitarian in the extreme. Trump, we thought, would at least start out appearing to be more like a regular president than a Big Brother type. This week the plan was to explore how he resembles a smooth-talking manipulator in Isaac Asimov\'s Foundation trilogy. ','send_date' => '2017-01-26 12:39:35','message_summary' => 'How Trump has already taken us into full-on \'Nineteen Eighty-Four\' territory','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '18','sender_ebox_id' => '1','subject' => 'How Trump has already taken us into full-on \'Nineteen Eighty-Four\' territory','message' => 'When we started the Dystopia Project two weeks ago, with the aim of writing a story on every dystopian novel that might apply to the Trump presidency, we figured it would be a while before we had reason to cover the heavyweight champ of the genre: Nineteen Eighty-Four. 

George Orwell\'s 1949 classic is about a state that is totalitarian in the extreme. Trump, we thought, would at least start out appearing to be more like a regular president than a Big Brother type. This week the plan was to explore how he resembles a smooth-talking manipulator in Isaac Asimov\'s Foundation trilogy. ','send_date' => '2017-01-26 12:44:38','message_summary' => 'How Trump has already taken us into full-on \'Nineteen Eighty-Four\' territory','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '19','sender_ebox_id' => '1','subject' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','message' => 'How Trump has already taken us into full-on \'Nineteen Eighty-Four\' territory','send_date' => '2017-01-26 12:54:58','message_summary' => 'd','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '20','sender_ebox_id' => '1','subject' => 'Google I/O 2017 dates are revealed by this freakishly hard puzzle','message' => 'Google\'s annual I/O developer conference will take place May 17 - 19 at Shoreline Amphitheater in Mountain View, California. 

Google being Google, it chose an unconventional way to reveal the date and the location for the conference: via a 5-part puzzle first announced on the Google Developers Twitter account. ','send_date' => '2017-01-26 13:05:58','message_summary' => 'Google I/O 2017 dates are revealed by this freakishly hard puzzle','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '21','sender_ebox_id' => '1','subject' => 'Samsung to unveil the Galaxy S8 in late March, new report claims','message' => 'Hot on the heels of the news that Samsung\'s Galaxy S8 won\'t launch in February comes a bevy of new rumors about the device, some of which contradict previous reports.

The Guardian published quite an in-depth report Tuesday, claiming Samsung will launch two devices in late March, with availability around April 21. These phones, codenamed "Dream" and "Dream 2," will be roughly the same size as Samsung\'s previous flagships, the Galaxy S7 and Galaxy S7 Edge, but will have larger, "infinity" displays, which will curve down on both sides of the phone. ','send_date' => '2017-01-26 13:09:12','message_summary' => 'Samsung to unveil the Galaxy S8 in late March, new report claims','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '22','sender_ebox_id' => '1','subject' => 'Test','message' => 'Test','send_date' => '2017-01-30 10:16:21','message_summary' => 'Test','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '23','sender_ebox_id' => '1','subject' => 'Test','message' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','send_date' => '2017-01-31 04:19:38','message_summary' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '24','sender_ebox_id' => '1','subject' => 'Test','message' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','send_date' => '2017-02-23 09:34:54','message_summary' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '25','sender_ebox_id' => '1','subject' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','message' => 'Short Message Service (SMS) is a text messaging service component of most telephone, World Wide Web, and mobile telephony systems.[1][1] It uses standardized communication protocols to enable mobile phone devices to exchange short text messages. An intermediary service can facilitate a text-to-voice conversion to be sent to landlines [2] SMS was the most widely used data application, with an estimated 3.5 billion active users, or about 80% of all mobile phone subscribers, at the end of 2010.[1]

SMS, as used on modern handsets, originated from radio telegraphy in radio memo pagers that used standardized phone protocols. These were defined in 1985 as part of the Global System for Mobile Communications (GSM) series of standards.[3][full citation needed] The protocols allowed users to send and receive messages of up to 160 alpha-numeric characters to and from GSM mobile handsets. Though most SMS messages are mobile-to-mobile text messages, support for the service has expanded to include other mobile technologies, such as ANSI CDMA networks and Digital AMPS.

SMS is also employed in mobile marketing, a type of direct marketing.[4] According to one market research report, as of 2014, the global SMS messaging business was estimated to be worth over $100 billion, accounting for almost 50 percent of all the revenue generated by mobile messaging.','send_date' => '2017-03-01 08:33:07','message_summary' => 'Please keep the message less than 141 characters. This is what will be delivered through SMS','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '26','sender_ebox_id' => '1','subject' => 'Test Alert ','message' => 'Sjdjdjdjdjdjjdjdjd ','send_date' => '2017-03-04 02:32:52','message_summary' => 'Description ','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '27','sender_ebox_id' => '1','subject' => 'afsd','message' => 'asdfasdfa','send_date' => '2017-03-11 16:58:28','message_summary' => 'asdfaf','draft' => '0','type' => NULL,'notification_type_id' => '1','data' => NULL),
            array('id' => '28','sender_ebox_id' => '2','subject' => 'Adjournment','message' => 'Test message from jairus to Gideon','send_date' => '2017-04-20 10:40:55','message_summary' => 'Summary Test Message','draft' => '0','type' => '1','notification_type_id' => '1','data' => NULL),
            array('id' => '29','sender_ebox_id' => '2','subject' => 'Case 1223 Fine','message' => 'Upon the hearing of your case number 1223 the Judge has ruled that you pay a fine of Ksh. 3,000.00 or face 2 days in Jail.','send_date' => '2017-04-20 11:03:02','message_summary' => 'Pay fine Ksh. 3,000.00 for Case No. 1223','draft' => '0','type' => '2','notification_type_id' => '2','data' => NULL)
        );

        $this->notifications = $notifications;
    }
}
